var specialCards = {
    "chest": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    "chance": [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 17, 18, 19],
    "fields": {
        "special": [0, 10, 20, 30],
        "chances": [7, 22, 36],
        "chests": [2, 17, 33],
    },
    "cards": {
        "1": "Idź na start",

        "2": "Bank się pomylił. Dostajesz 200$",
        "3": "Płacisz rachunek za lekarza. Zapłać 50$",
        "4": "Za sprzedaż udziałów dostajesz 50$",

        "5": "Wyjdź z więzienia",
        "6": "Idziesz do więzienia",

        "7": "Dostajesz po 50$ od każdego z graczy",
        "8": "Dostajesz 100$ jako prezent na święta",
        "9": "Zwrot podatku. Dosatjesz 20$",
        "10": "Są Twoje urodziny. Dostajesz 10$ od każdego z graczy",
        "11": "Wypłata ubezpieczenia. Dostajesz 100$",
        "12": "Rachunki ze szpitala. Zapłać 50$",
        "13": "Rachunki ze szkoły. Zapłać 50$",
        "14": "Otrzymujesz 25$ za konsultacje",

        "15": "Musisz zapłacić za naprawę ulicy. Płacisz 40$ za każdy dom oraz 115$ za każy hotel który posiadasz",

        "16": "Dostajesz w spadku 100$",




        "17": "Idź na start", 
        "18": "Idź do Illinois",
        "19": "Idź do St. Charles Place",
        "20": "Idź do najbliższej placówki, jeśli nie jest kupiona możesz ją kupić jeśli jest kupiona zapłać właścicielowi",
        "21": "Idź do najbliższych kolei, jeśli nie są kupione możesz je kupić jeśli jest kupiona zapłać właścicielowi",

        "22": "Bank wypłaca Ci 50$",

        "23": "Wyjdź z więzienia",
        "24": "Cofnij się o 3 pola",
        "25": "Idź prosto do więzienia",
        "26": "Robisz remont generalnych swoich posiadłości. Za każdy dom zapłać 25$ a za każdy hotel 100$",

        "27": "Zapłac podatek w wysokości 15$",

        "28": "Idź do Południowych kolei",
        "29": "Idź do Board Walk",

        "30": "Płacisz każdemu z graczy 50$", 
        "31": "Dostajesz 150$",
        "32": "Wygrywasz konkurs krzyżówek. Dostajesz 100$"
    }
    //15 26 to do
};

var property = {
    "1" : {
        "color" : "brown",
        "name" : "Mediter",
        "value" : 120,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 100,
        "hotel_price" : 100,
        "price_default" : 5,
        "house_price_pay_1" : 40,
        "house_price_pay_2" : 60,
        "house_price_pay_3" : 160,
        "house_price_pay_4" : 320,
        "hotel_price_pay" : 500,
        "own" : " "
    },
    "2" : {
        "color" : "white",
        "name" : "Chest",
        "value" : "chest",
        "own" : " "
    },
    "3" : {
        "color" : "brown",
        "name" : "Baltic",
        "value" : 120,
        "house" : 1,
        "hotel" : 1,
        "house_price" : 100,
        "hotel_price" : 100,
        "price_default" : 10,
        "house_price_pay_1" : 40,
        "house_price_pay_2" : 120,
        "house_price_pay_3" : 360,
        "house_price_pay_4" : 640,
        "hotel_price_pay" : 900,
        "own" : " "
    },
    "4" : {
        "color" : "white",
        "name" : "Tax",
        "value" : "Pay",
        "own" : " "
    },
    "5" : {
        "color" : "black",
        "name" : "Railroad S",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "own" : " "
    },
    "6" : {
        "color" : "lightblue",
        "name" : "Oriental",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 100,
        "hotel_price" : 100,
        "price_default" : 15,
        "house_price_pay_1" : 60,
        "house_price_pay_2" : 180,
        "house_price_pay_3" : 540,
        "house_price_pay_4" : 800,
        "hotel_price_pay" : 1100,
        "own" : " "
    },
    "7" : {
        "color" : "white",
        "name" : "Chance",
        "value" : "Chance",
        "own" : " "
    },
    "8" : {
        "color" : "lightblue",
        "name" : "Vermont",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 100,
        "hotel_price" : 100,
        "price_default" : 15,
        "house_price_pay_1" : 60,
        "house_price_pay_2" : 180,
        "house_price_pay_3" : 540,
        "house_price_pay_4" : 800,
        "hotel_price_pay" : 1100,
        "own" : " "
    },
    "9" : {
        "color" : "lightblue",
        "name" : "Connecticut",
        "value" : 240,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "house_price_pay_1" : 80,
        "house_price_pay_2" : 200,
        "house_price_pay_3" : 600,
        "house_price_pay_4" : 900,
        "hotel_price_pay" : 1200,
        "own" : " "
    },
    "10" : {
        "color" : "white",
        "name" : "Jail",
        "value" : "Fuck off",
        "own" : " "
    },
    "11" : {
        "color" : "pink",
        "name" : "St. Charles Place",
        "value" : 280,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 20,
        "house_price_pay_1" : 100,
        "house_price_pay_2" : 300,
        "house_price_pay_3" : 900,
        "house_price_pay_4" : 1250,
        "hotel_price_pay" : 1500,
        "own" : " "
    },
    "12" : {
        "color" : "#CDF0AE",
        "name" : "Power plant",
        "value" : 150,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "own" : " "
    },
    "13" : {
        "color" : "pink",
        "name" : "States",
        "value" : 280,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 20,
        "house_price_pay_1" : 100,
        "house_price_pay_2" : 300,
        "house_price_pay_3" : 900,
        "house_price_pay_4" : 1250,
        "hotel_price_pay" : 1500,
        "own" : " "
    },
    "14" : {
        "color" : "pink",
        "name" : "Virginia",
        "value" : 320,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 25,
        "house_price_pay_1" : 120,
        "house_price_pay_2" : 360,
        "house_price_pay_3" : 1000,
        "house_price_pay_4" : 1400,
        "hotel_price_pay" : 1800,
        "own" : " "
    },
    "15" : {
        "color" : "black",
        "name" : "Railroad W",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "own" : " "
    },
    "16" : {
        "color" : "orange",
        "name" : "St.James Place",
        "value" : 360,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 30,
        "house_price_pay_1" : 140,
        "house_price_pay_2" : 400,
        "house_price_pay_3" : 1100,
        "house_price_pay_4" : 1500,
        "hotel_price_pay" : 1900,
        "own" : " "
    },
    "17" : {
        "color" : "white",
        "name" : "Chest",
        "value" : "chest",
        "own" : " "
    },
    "18" : {
        "color" : "orange",
        "name" : "Tennesse",
        "value" : 360,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 30,
        "house_price_pay_1" : 140,
        "house_price_pay_2" : 400,
        "house_price_pay_3" : 1100,
        "house_price_pay_4" : 1500,
        "hotel_price_pay" : 1900,
        "own" : " "
    },
    "19" : {
        "color" : "orange",
        "name" : "New York",
        "value" : 400,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 200,
        "hotel_price" : 200,
        "price_default" : 35,
        "house_price_pay_1" : 160,
        "house_price_pay_2" : 440,
        "house_price_pay_3" : 1200,
        "house_price_pay_4" : 1600,
        "hotel_price_pay" : 2000,
        "own" : " "
    },
    "20" : {
        "color" : "white",
        "name" : "Parking",
        "value" : "none",
        "own" : " "
    },
    "21" : {
        "color" : "red",
        "name" : "Kentucky",
        "value" : 440,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 35,
        "house_price_pay_1" : 180,
        "house_price_pay_2" : 500,
        "house_price_pay_3" : 1400,
        "house_price_pay_4" : 1750,
        "hotel_price_pay" : 2100,
        "own" : " "
    },
    "22" : {
        "color" : "white",
        "name" : "chance",
        "value" : "Chance",
        "own" : " "
    },
    "23" : {
        "color" : "red",
        "name" : "Indiana",
        "value" : 440,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 35,
        "house_price_pay_1" : 180,
        "house_price_pay_2" : 500,
        "house_price_pay_3" : 1400,
        "house_price_pay_4" : 1750,
        "hotel_price_pay" : 2100,
        "own" : " "
    },
    "24" : {
        "color" : "red",
        "name" : "Illinois",
        "value" : 480,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 40,
        "house_price_pay_1" : 200,
        "house_price_pay_2" : 600,
        "house_price_pay_3" : 1500,
        "house_price_pay_4" : 1850,
        "hotel_price_pay" : 2200,
        "own" : " "
    },
    "25" : {
        "color" : "black",
        "name" : "Railroad N",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "own" : " "
    },
    "26" : {
        "color" : "yellow",
        "name" : "Atlantic",
        "value" : 520,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 45,
        "house_price_pay_1" : 220,
        "house_price_pay_2" : 660,
        "house_price_pay_3" : 1600,
        "house_price_pay_4" : 1950,
        "hotel_price_pay" : 2300,
        "own" : " "
    },
    "27" : {
        "color" : "yellow",
        "name" : "Ventnor",
        "value" : 520,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 45,
        "house_price_pay_1" : 220,
        "house_price_pay_2" : 660,
        "house_price_pay_3" : 1600,
        "house_price_pay_4" : 1950,
        "hotel_price_pay" : 2300,
        "own" : " "
    },
    "28" : {
        "color" : "#CDF0AE",
        "name" : "Water Works",
        "value" : 150,
        "price_default" : 10,
        "own" : " "
    },
    "29" : {
        "color" : "yellow",
        "name" : "Marvin",
        "value" : 560,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 300,
        "hotel_price" : 300,
        "price_default" : 50,
        "house_price_pay_1" : 240,
        "house_price_pay_2" : 720,
        "house_price_pay_3" : 1700,
        "house_price_pay_4" : 2050,
        "hotel_price_pay" : 2400,
        "own" : " "
    },
    "30" : {
        "color" : "white",
        "name" : "JAIL",
        "value" : "none",
        "own" : " "
    },
    "31" : {
        "color" : "green",
        "name" : "Pacific",
        "value" : 600,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 400,
        "hotel_price" : 400,
        "price_default" : 55,
        "house_price_pay_1" : 260,
        "house_price_pay_2" : 780,
        "house_price_pay_3" : 1900,
        "house_price_pay_4" : 2200,
        "hotel_price_pay" : 2550,
        "own" : " "
    },
    "32" : {
        "color" : "green",
        "name" : "North Carolina",
        "value" : 600,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 400,
        "hotel_price" : 400,
        "price_default" : 55,
        "house_price_pay_1" : 260,
        "house_price_pay_2" : 780,
        "house_price_pay_3" : 1900,
        "house_price_pay_4" : 2200,
        "hotel_price_pay" : 2550,
        "own" : " "
    },
    "33" : {
        "color" : "white",
        "name" : "chest",
        "value" : "Chest",
        "own" : " "
    },
    "34" : {
        "color" : "green",
        "name" : "Pensylvania",
        "value" : 640,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 400,
        "hotel_price" : 400,
        "price_default" : 60,
        "house_price_pay_1" : 300,
        "house_price_pay_2" : 900,
        "house_price_pay_3" : 2000,
        "house_price_pay_4" : 2400,
        "hotel_price_pay" : 2800,
        "own" : " "
    },
    "35" : {
        "color" : "black",
        "name" : "Railroad E",
        "value" : 200,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 40,
        "hotel_price" : 200,
        "price_default" : 200,
        "own" : " "
    },
    "36" : {
        "color" : "white",
        "name" : "chance",
        "value" : "none",
        "own" : " "
    },
    "37" : {
        "color" : "blue",
        "name" : "Park Place",
        "value" : 700,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 400,
        "hotel_price" : 400,
        "price_default" : 70,
        "house_price_pay_1" : 350,
        "house_price_pay_2" : 1000,
        "house_price_pay_3" : 2200,
        "house_price_pay_4" : 2600,
        "hotel_price_pay" : 3000,
        "own" : " "
    },
    "38" : {
        "color" : "white",
        "name" : "TAX",
        "value" : "Luxury",
        "own" : " "
    },
    "39" : {
        "color" : "blue",
        "name" : "Board Walk",
        "value" : 800,
        "house" : 0,
        "hotel" : 0,
        "house_price" : 400,
        "hotel_price" : 400,
        "price_default" : 100,
        "house_price_pay_1" : 400,
        "house_price_pay_2" : 1200,
        "house_price_pay_3" : 2800,
        "house_price_pay_4" : 3400,
        "hotel_price_pay" : 4000,
        "own" : " "
    }
};